### ISSUE TITLE
Plum ecomax 920 p1

### ISSUE THREAD

**Issue by genrihb** [denpamusic/homeassistant-plum-ecomax#30]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I'm having the following issue:

![Screenshot_2023-07-08-17-36-45-296_com android chrome](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/105509954/542e71bf-8779-4514-b9ef-b3d3c0a7d1f7)
![Screenshot_2023-07-08-17-37-21-058_com android chrome](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/105509954/40a37871-5ce0-4e28-8156-bf41ebeec171)
![Screenshot_2023-07-08-17-37-24-414_com android chrome](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/105509954/ed65accf-ce1e-49db-b8e1-3b783b270a89)
![Screenshot_2023-07-08-17-37-46-447_com android chrome](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/105509954/5bc5d2d5-f21c-4650-8ae8-976233970179)
![Screenshot_2023-07-08-17-38-02-846_com android chrome](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/105509954/dd8e0a92-c786-49bc-b3c6-9abda630834a)
![Screenshot_2023-07-08-17-38-11-244_com android chrome](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/105509954/bc43bba0-d691-4b31-bfa0-53b7fa357927)
Here are all the settings and I don't understand what's going on.  Tried to change the protocol to modbus, frames.  Changed baudrate.  Nothing.  Installation via hass.  Home assistant installed on debian 11.Home Assistant 2023.5.2
 Supervisor 2023.07.1
 UI 20230503.3 - latest

### I have following devices connected:

- [ ] ecoMAX 3xx series
- [ ] ecoMAX 8xx series
- [X] ecoMAX 9xx series
- [ ] Expansion module B
- [ ] Expansion module C
- [ ] ecoSTER 200/ecoSTER Touch
- [ ] ecoLAMBDA
- [ ] ecoNET 300

### I'm connecting to my devices using:

Ethernet/WiFi to RS-485 converter

### I'm seeing following log messages:

```shell
Logger: pyplumio.protocol
Source: runner.py:179
First occurred: 7 июля 2023 г. в 22:21:31 (111 occurrences)
Last logged: 17:34:22

Can't process received frame: Incorrect frame checksum (0)
Can't process received frame: Incorrect frame checksum (135)
Can't process received frame: Incorrect frame checksum (108)
Can't process received frame: Incorrect frame checksum (255)
Can't process received frame: Incorrect frame checksum (6)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by genrihb** [comment]
Эта ошибка возникла в кастомной интеграции.

Logger: custom_components.plum_ecomax.config_flow
Source: custom_components/plum_ecomax/config_flow.py:174
Integration: Plum ecoMAX (documentation, issues)
First occurred: 7 июля 2023 г. в 14:55:46 (17 occurrences)
Last logged: 17:33:09

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/plum_ecomax/config_flow.py", line 190, in async_step_device
    await self.device_task
  File "/config/custom_components/plum_ecomax/config_flow.py", line 174, in _wait_for_device
    self.device: Addressable = await self.connection.get(
  File "/usr/local/lib/python3.10/site-packages/pyplumio/helpers/event_manager.py", line 38, in get
    await self.wait_for(name, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/pyplumio/helpers/event_manager.py", line 34, in wait_for
    await asyncio.wait_for(self.create_event(name).wait(), timeout=timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

**Comment by denpamusic** [comment]
Hi,

Thanks for the feedback!

Timeout error is normal in this case, it occurs, because device failed to reply in reasonable time.

From your log, it seems that for some reason, PyPlumIO hasn't been able to decode data it's seeing from the EM. Since I've seen this integration being successfully used with your EM model before, I assume it should be able to work with it. There's couple things to try to address this issue.

Firstly ensure that you connected the converter to the correct port on your EM device. On EM920 this port usually labeled G2 or just lookup instructions on how to connect ecoNET300 to your particular model and use the same port.
Also try swapping A and B wires (D+, D-) and restart the converter device.
Normally it is
```
[A]     ->  [D+]
[B]     ->  [D-]
```
but sometimes they are mislabeled on the cheap Chinese convertor devices, so it's better to try it anyway.

If that doesn't help, try following changes in the converter configuration:
1. In the `Socket Settings` section, set `Keep Alive (s)` to **0** and set `Timeout(s)` to some reasonable value like **20 seconds**. This ensures that connection attempts doesn't overwhelm device, because otherwise any connection attempt will be stuck forever. While you're there increase `Buffer Size` to **1024**, ecoMAX can send pretty lengthy packets of up to 1000 bytes.
2. In the `Buffer Settings` on `Serial Port Settings` page increase `Buffer Size` to at least **1024** and decrease `Gap Time` to **30**. In `Cli Settings` on the same page, set `Cli` to **disable**.
3. Reboot the converter device.

Hope that helps to resolve the issue!

**Comment by genrihb** [comment]
denpamusic, thank so match. Your advice worked.  Thanks for explaining the settings.

**Comment by denpamusic** [comment]
You are welcome!

I really should write at least some guide on settings in the README, hovewer it's difficult to do, since every converter's UI is different. Probably it's best to compile a list of 2-3 recommended converters that are proven to work and settings for them...

Anyways, glad that I could help! Feel free to contact me if any other problem arises.

--
Best Regards,
Denis Paavilainen
