### ISSUE TITLE
Wrong weather and mixer circuit switch.

### ISSUE THREAD

**Issue by zASSAz** [denpamusic/homeassistant-plum-ecomax#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I'm having the following issue:

ecoMAX 850i:
1) Mixer circuit turn On/Off [enable/disable] switch acts like weather control on/off for that mixer.
2) Mixer circuit turn On/Off [enable/disable] switch is missing.

### I have following devices connected:

- [ ] ecoMAX 3xx series
- [X] ecoMAX 8xx series
- [ ] ecoMAX 9xx series
- [ ] Expansion module B
- [ ] Expansion module C
- [X] ecoSTER 200/ecoSTER Touch
- [ ] ecoLAMBDA
- [ ] ecoNET 300

### I'm connecting to my devices using:

Ethernet/WiFi to RS-485 converter

### My diagnostics data:

[config_entry-plum_ecomax-65c192f8487e12041244d9849d7dc98f.json.txt](https://github.com/denpamusic/homeassistant-plum-ecomax/files/13031263/config_entry-plum_ecomax-65c192f8487e12041244d9849d7dc98f.json.txt)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
Hi,

Thanks for the feedback!

Now that's a quite intriguing way for it to fail. I believe the prime suspect would be incorrect order of parameters for ecoMAX i in the parameter's decoder.

Could you please download diagnostics two times: first when mixer is enabled, second when mixer is disabled via the controller. Send me both diagnostic files to: denpa@denpa.pro. This way we'll hopefully be able to tell which parameters got mixed up in the decoder.

Thanks beforehand!

**Comment by denpamusic** [comment]
I think I found the issue.
I somehow accidentally removed one parameter in this commit: https://github.com/denpamusic/PyPlumIO/commit/a33e3c7f98fc932d2ec20795240148dc820bb696

This has now been added back and should resolve the issue.

**Comment by denpamusic** [comment]
Something else I noticed while working out this issue - both H2 and H3 circuit switch cannot be simple binary switches due to the having three possible values for the same parameter.

Those excerpts from the EM850i manual describe the `support` parameter:
![Screenshot of the H1 circuit section from the ecoMAX850i4 manual](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/16575433/a01c5c22-b3be-42d0-87be-6792982813d1)

![Screenshot of the H2 circuit section from the ecoMAX850i4 manual](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/16575433/7675c07e-2d00-4273-8f9f-2a36a8f29699)

The https://github.com/denpamusic/homeassistant-plum-ecomax/commit/7cb25def82bfe50d8eebe1c7602be793c7e2736f commit ensures, that binary switch is added only for the H1, while H2 and H3 will have a selector.
