### ISSUE TITLE
Ash pan level support for ecoMAX 860P3-S LITE

### ISSUE THREAD

**Issue by dareksliwecki** [denpamusic/homeassistant-plum-ecomax#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I want to suggest:

- [ ] support for a new product
- [X] new functionality for a product
- [ ] documentation improvement
- [ ] other

### Feature description

I use integration to communicate with the ecoMAX 860P3-S LITE controller. Using [PyPlumIO](https://github.com/denpamusic/PyPlumIO) library I discovered that frame 215 is responsible for reporting the level of filling ash pan.
Is it possible to add entity support for this controller model?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
Hi,

Thank you very much for the feedback and research!

It's possible to add this sensor, although I will need [diagnostics](https://www.home-assistant.io/integrations/diagnostics/) data from the integration in order to extract numerical model id for your controller. You can attach it via comments here or send it to denpa@denpa.pro.

**Comment by denpamusic** [comment]
Thanks for the diagnostics! 

This has now been added as device-specific regdata sensor in this commit https://github.com/denpamusic/homeassistant-plum-ecomax/commit/cbf58c3877ae14c892449498976e5e1c6dac05ef.

Additionally, it seems that product IDs are only unique for base models, so EM860P-O and your EM860P-S, have exactly same ID 51 as they are both EM860P. To avoid collisions, I've redone the filter to work on full model string instead of product IDs.

You can now wait for a stable release or test it right now by [installing the main branch](https://github.com/denpamusic/homeassistant-plum-ecomax/issues/35)!

Thanks again for your help!

**Comment by dareksliwecki** [comment]
Works great! 
Thanks for such quick update.

**Comment by denpamusic** [comment]
> Thanks for such quick update.

You're welcome! Glad that everything works!
Feel free to contact me if you need anything else added.
