### ISSUE TITLE
The "get parameter service" to be able to respond only with the actual value 

### ISSUE THREAD

**Issue by niq83** [denpamusic/homeassistant-plum-ecomax#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I want to suggest:

- [ ] support for a new product
- [ ] new functionality for a product
- [ ] documentation improvement
- [ ] other

### Feature description

It would be useful to be able to get only the "value" from get parameter. 
Maybe even create an entity that modifies one parameter and then cheks the value 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
Hi,

Thank you for the feedback!

You can actually get the value from the service response by simply accessing it as dict, for example `response["value"]`.
Creating an entity based on service is not recommended, since services are mostly meant for automations.

That being said, ability to add custom entities (sensors, binary sensors and numbers) is currently being worked on in the [options_flow](https://github.com/denpamusic/homeassistant-plum-ecomax/tree/options_flow) branch and will be available in v0.4.2.

You can see some screenshots of the configuration menu prototype below (number entities, will be added later):

## Main menu
![Screenshot of an option flow 1](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/16575433/a84379a8-027a-4326-9b8a-2c0fe239d93d)

## Selecting entity type
![Screenshot of an option flow 2](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/16575433/3d4ca5df-8aa2-48ec-9891-b38c136d2719)

## Selecting new entity type
![Screenshot of an option flow 3](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/16575433/531fd688-1d39-415c-bd21-3017da10ef3e)

## Filing in new entity details
![Screenshot of an option flow 4](https://github.com/denpamusic/homeassistant-plum-ecomax/assets/16575433/ee0bbf18-63fd-437f-aa24-09b1cbc5f987)

**Comment by denpamusic** [comment]
As this feature was previously discussed in #41
I'll open a new issue and close both this issue and #41, to have only one place to track progress.
