### ISSUE TITLE
What Serial Brige to Streem? 

### ISSUE THREAD

**Issue by gigipawel** [denpamusic/homeassistant-plum-ecomax#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I want to suggest:

- [ ] support for a new product
- [ ] new functionality for a product
- [ ] documentation improvement
- [ ] other

### Feature description

What gateway do you use to connect to this app? Tasmota, EspHome or other? ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
Sorry for late response, couldn't access GitHub website while traveling😔

While tasmota's [Serial to TCP bridge feature](https://tasmota.github.io/docs/Serial-to-TCP-Bridge/) should work, I recommend a dedicated R485 to Ethernet/WiFi converter device. They are readily available at very affordable prices. Just google "RS485 to WiFi" and you should find a bunch.

**Comment by snsmakel** [comment]
Hi,

How could I use econet300 which is delivered with the boiler? It can be reached at least on port 80 at local network, but this integration cannot connect to that ip (timeout).

Regards
 Severi

**Comment by denpamusic** [comment]
> Hi,
> 
> How could I use econet300 which is delivered with the boiler? It can be reached at least on port 80 at local network, but this integration cannot connect to that ip (timeout).
> 
> Regards Severi

Hi,

Sorry, but this integration and underlying PyPlumIO library are made to work directly with ecoMAX controllers through RS485 and RS485 to TCP converters without the need for ecoNET300 (EN) device.

Currently there's no plan to support EN device through this integration, since it's API is vastly different. It's probably better to create separate integration to work with EN, instead of cramming two different implementations into this one.
