### ISSUE TITLE
Ecomax 850I support

### ISSUE THREAD

**Issue by zASSAz** [denpamusic/homeassistant-plum-ecomax#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I want to suggest:

- [X] support for a new product
- [ ] new functionality for a product
- [ ] documentation improvement
- [ ] other

### Feature description

I have Ecomax 850i3 standalone controller. It will be fine to have this controller supported. Can assist of getting required information for implementation.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
As far as general device support concerned, I've answered you in [PyPlumIO issue](https://github.com/denpamusic/PyPlumIO/issues/5).

Hovewer, if you want specific sensors that are provided by EM850i, but are missing in HASS, you might want to setup this integration in HASS and send me diagnostics data to denpa@denpa.pro, as described [here](https://www.home-assistant.io/integrations/diagnostics/).

**Comment by zASSAz** [comment]
Seems to be Mixer Target Temperature control is not working under mixer.Does not show temperature and if I try to move the bar shows : number/set_value. required key not provided @ data['value'] 
Mixer sensors are working as required.

**Comment by denpamusic** [comment]
Please post diagnostics data for the integration here as a attachment on  <a href="mailto:denpa@denpa.pro?subject=ecoMAX 850i diagnostic data">send it via email</a>.
Sadly I don't have any mixers myself, so I'll need to have this data in order to track down the problem.
Thank you beforehand!

**Comment by denpamusic** [comment]
Sorry for long wait, but I think I figured out the issue with missing mixer parameters. Basically PyPlumIO was not requesting all available parameters, but only ones recently changed on the device. This is [fixed](https://github.com/denpamusic/PyPlumIO/commit/9efb274e50d45c3441dc60e873ee70b15b140b43) now.

However as I am not totally sure that this is only thing that was causing the issue, for a time being I decided against releasing new HASS integration version with this change.

Instead I released PyPlumIO v0.2.30, that basically includes only this one fix and made `main` branch of HASS integration depend on it. If we'll find out that the mixer parameters issue is fixed with this, I'll release new version of HASS integration otherwise we'll continue to dig deeper into the problem.
This way we can avoid forcing users to install an update, that might not even do anything for them😉

So if you're still willing to help, please install `main` branch via hacs as I described [here](https://github.com/denpamusic/homeassistant-plum-ecomax/issues/1#issuecomment-1334489848) and check whether target temperature control is working for you or not. Once you do, please send diagnostics again, regardless of if it's working or not, and I'll figure out where to go next from there.

As always, thanks for your help!👍

**Comment by denpamusic** [comment]
I've added some more controllable parameters on 850i and standardized display names for circuits.
I think this can be safely closed now.
If you need more parameters added, feel free to let me know and reopen this.
