### ISSUE TITLE
ecoNET300

### ISSUE THREAD

**Issue by jontofront** [denpamusic/homeassistant-plum-ecomax#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I want to suggest:

- [X] support for a new product
- [ ] new functionality for a product
- [ ] documentation improvement
- [ ] other

### Feature description

I got with boiler with [Regulator ecoMAX800P](https://www.plum.pl/en/project/ecomax800p_en/). And I remotely connect by econect ecoNET300 remotely by web and locally by IP address. Does this library support this ecoNET300 device by TCP (I mean locally)?

### Webpage of the product, that I'm suggesting:

https://www.plum.pl/en/project/econet300_en/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Taziff** [comment]
I'm in the same situation and IT would be nice to be able to integrate via EcoNET300

**Comment by denpamusic** [comment]
Hi,

Thank you for your suggestion!

Sorry, but as I mentioned earlier in the [different issue](https://github.com/denpamusic/homeassistant-plum-ecomax/issues/6#issuecomment-1300212290) this integration doesn't support ecoNET300 (EN). This is to avoid over-complicating underlying PyPlumIO library with handling of two completely different protocols. PyPlumIO by design was made as an __alternative/replacement__ to the EN, based on the official EN firmware to handle native low-level ecoMAX serial protocol either via TCP or via RS485 serial connection. EN protocol on the other hand is a high-level JSON API.

If this integration is to ever support EN, I believe that correct way to do it, will be to develop separate library to work specifically with EN API and depend on it alongside with PyPlumIO. This way each library can be developed and used separately by Python community and selection of which library to use for communication could be handled within the HASS integration.

It shoudn't really be that hard to develop such a library and I can use the very same EN firmware that I used to develop PyPlumIO to compile JSON API reference for ecoNET300. Testing of it will be whole other issue though, since I don't have EN device myself, nor any plans to get it in the near future. For now I'll add this feature to the project's roadmap, probably for the next major version.

That being said, for now you can simply connect RS485 adapter or converter in parallel with the EN300 and use HASS integration this way.

**Comment by jontofront** [comment]
Thanks for the quick response. IF I have the cable from RS485 to USB maybe you know which hardware work with this code?

**Comment by jontofront** [comment]
https://github.com/denpamusic/homeassistant-plum-ecomax/issues/6#6#

**Comment by denpamusic** [comment]
You have a couple of options.

If you use RS485 to USB adapter (one in the photo below is just an example, any devices advertised as RS485 to USB adapter/converter should work), it means that you must connect directly to the device that is running Home Assistant. So for requirements for hardware is the same as for Home Assistant.

![usb-to-rs485-4](https://user-images.githubusercontent.com/16575433/205437781-ea9205be-0815-4869-8332-24eca867f58c.jpg)

I you didn't have Home Assistant yet, I find that Raspberry Pi 4B with 4Gb of RAM can run HASS well enough, even in docker container. So I'd start with that.

To connect RS485 to USB adapter you must connect A(+) on adapter to D+ pin on ecoMAX, B(-) on adapter to D- pin on ecoMAX and GND on adapter to GND pin on ecoMAX to the same socket that you connected your ecoNET300 or ecoSTER panel. 
```
Adapter ->  ecoMAX
[A]     ->  [D+]
[B]     ->  [D-]
[GND]   ->  [GND]
```

Of course it means, that hardware that runs your Home Assistant must be pretty close to the ecoMAX controller, since it needs to be connected by wire to it.

Other way is to buy RS485 to WiFi converter, like one in the picture.
![604-700x700](https://user-images.githubusercontent.com/16575433/205438519-171a555c-79db-45f4-8a71-a0469de06f0b.jpg)
Connection scheme is the same as with the USB adapter, but they have an advantage of providing ability to connect to the ecoMAX controller through wireless connection via TCP, so the hardware that runs HASS can be installed anywhere.

Those can easily be sourced at dirt cheap prices from China.
For example, I'm using Elfin EW11, that costed me "whooping" 12 euros and never had any problems with it :)

There are third, more advanced way, of using RS485 to USB adapter and ser2net software to essentially build your own RS485 to WiFi converter, however with the amount of factory-made solutions I don't think there is a reason to bother with it.

**Comment by pblxptr** [comment]
@jontofront if you want support for ecoNET300 you can have a look at this - https://github.com/pblxptr/ecoNET-300-Home-Assistant-Integration I've been working on this in my free time. I wouldn't even call it a pre-alpha version, but I should create the first release in a few weeks (if I find the time). You can try it on your own, or you can subscribe for changes and wait until the first release and then check it.

**Comment by denpamusic** [comment]
@pblxptr 
Awesome!
I frequently get requests for EN300 support in HASS, glad to see that there's some work being done on it.
Also props for using coordinator - great for future-proofing!👍

Can I mention your integration in the readme?
Once I get around to compile faq that is, xmas is always busy😅

**Comment by pblxptr** [comment]
@denpamusic  sure you can mention it :) The more people find it, the better feedback I will probably get which will allow preparing a better implementation. Thanks! :)

**Comment by jontofront** [comment]
thanks, it's the first step.  good job.
